---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.3
before_install:
  - gem install bundler -v 2.0.2
  - gem install ripper-tags -v 0.8.1
  - brew unlink python@2
  - brew install --HEAD universal-ctags/universal-ctags/universal-ctags
os: osx
