# which command to use to generate tags for a specific file extension
# overrides default_command
# tag generation commands must support --append, -f, -L
# NOTE: Exuberant-ctags does NOT satisfy this requirement, instead use Universal-ctags
#
# Default: empty
extension_commands:
  rb: ripper-tags
  c: ctags
  go: gotags

# default command to generate tags
# command must support --append, -f, -L
#
# Default: ctags
default_command: ctags

# filename (relative to pwd) to generate tags into
#
# Default: tags
tagf: tags

# list of extensions to exclusively generate tags for
# this will take precendence over extensions_blacklist if it is non-empty
#
# Default: []
extensions_whitelist: [rb, c, h, js]

# list of extensions to not generate tags for
# this can will be ignored if extensions_whitelist is non-empty
#
# Default: []
extensions_blacklist: [erb, html, txt]

# which paths (relative to pwd) to ignore
# It's usually better to avoid this since tagrity integrates with git by
# default using the strategy specified by git_strategy
#
# Default: []
excluded_paths: [vendor, node_modules]
